### ISSUE TITLE
ModuleNotFoundError: No module named 'libpymo'

### ISSUE THREAD

**Issue by fmbao** [quic/aimet#1166]
Try any method,but throw the error:
`Traceback (most recent call last):
  File "deepspeech2_quanteval.py", line 36, in <module>
    from aimet_common.defs import QuantScheme
  File "/usr/local/lib/python3.6/dist-packages/aimet_common/defs.py", line 46, in <module>
    import libpymo
ModuleNotFoundError: No module named 'libpymo'
`

**Comment by quic-ssiddego** [comment]
Hi @fmbao could you please share the steps you followed? Adding @quic-bharathr  to follow-up further.

**Comment by fmbao** [comment]
Hi  @quic-ssiddego, I install environment software follow your doc in aimet. My pc is ubuntu 18.04 && RTX 2070.The following  is my install.sh
```shell

#!/bin/bash

sudo -H apt-get update
sudo -H apt-get install python3.6 python3.6-dev python3-pip
sudo -H python3 -m pip install --upgrade pip



wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-ubuntu1804.pin
mv cuda-ubuntu1804.pin /etc/apt/preferences.d/cuda-repository-pin-600
wget https://developer.download.nvidia.com/compute/cuda/11.1.1/local_installers/cuda-repo-ubuntu1804-11-1-local_11.1.1-455.32.00-1_amd64.deb
dpkg -i cuda-repo-ubuntu1804-11-1-local_11.1.1-455.32.00-1_amd64.deb
sudo -H apt-key add /var/cuda-repo-ubuntu1804-11-1-local/7fa2af80.pub
echo "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64 /" > /etc/apt/sources.list.d/cuda.list
echo "deb https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64 /" > /etc/apt/sources.list.d/nvidia-ml.list
sudo -H apt-get update
sudo -H apt-get -y install cuda

wget http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb
sudo -H apt-get --assume-yes install ./nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb
sudo -H apt-get update


export AIMET_VARIANT="torch_gpu"

export release_tag="1.20.0"

export download_url="https://github.com/quic/aimet/releases/download/${release_tag}"

export wheel_file_suffix="cp36-cp36m-linux_x86_64.whl"


sudo -H python3 -m pip install ${download_url}/AimetCommon-${AIMET_VARIANT}_${release_tag}-${wheel_file_suffix}

# Install ONE of the following depending on the variant
sudo -H python3 -m pip install ${download_url}/AimetTorch-${AIMET_VARIANT}_${release_tag}-${wheel_file_suffix} -f https://download.pytorch.org/whl/torch_stable.html

sudo -H python3 -m pip install ${download_url}/Aimet-${AIMET_VARIANT}_${release_tag}-${wheel_file_suffix}


cat /usr/local/lib/python3.6/dist-packages/aimet_common/bin/reqs_deb_common.txt | xargs sudo -H  apt-get --assume-yes install


cat /usr/local/lib/python3.6/dist-packages/aimet_torch/bin/reqs_deb_torch_gpu.txt | xargs sudo -H  apt-get --assume-yes install



sudo -H python3 -m pip uninstall -y pillow
sudo -H python3 -m pip install --no-cache-dir Pillow-SIMD==7.0.0.post3



ln -s /usr/lib/x86_64-linux-gnu/libjpeg.so /usr/lib

# If you installed the CUDA 11.x drivers
ln -s /usr/local/cuda-11.0 /usr/local/cuda
# OR if you installed the CUDA 10.x drivers
ln -s /usr/local/cuda-10.0 /usr/local/cuda

source /usr/local/lib/python3.6/dist-packages/aimet_common/bin/envsetup.sh
```

**Comment by fmbao** [comment]
@quic-bharathr Please help me. Thanks.

**Comment by fmbao** [comment]
Meanwhile,I execute install.sh by sudo su into root env.

**Comment by fmbao** [comment]
I test import code in terminal, same error. Like this:
```shell
Python 3.6.9 (default, Mar 15 2022, 13:55:28) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from aimet_torch.quantsim import QuantizationSimModel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/aimet_torch/quantsim.py", line 53, in <module>
    from aimet_common.defs import QuantScheme, QuantizationDataType
  File "/usr/local/lib/python3.6/dist-packages/aimet_common/defs.py", line 46, in <module>
    import libpymo
ModuleNotFoundError: No module named 'libpymo'
>>> from aimet_common.defs import QuantScheme
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/aimet_common/defs.py", line 46, in <module>
    import libpymo
ModuleNotFoundError: No module named 'libpymo'
```

**Comment by tucachmo2202** [comment]
> ```shell
> source /usr/local/lib/python3.6/dist-packages/aimet_common/bin/envsetup.sh
> ```

Hi, may you should activate the environment:
```
source /usr/local/lib/python3.6/dist-packages/aimet_common/bin/envsetup.sh
```

**Comment by shivSD** [comment]
@fmbao  were you able to resolve this issue ?

**Comment by quic-sendilk** [comment]
please retry in the newer release and reopen its still an issue.
