### ISSUE TITLE
libaimet_tf_ops.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Jia-HongHenryLee** [quic/aimet#1370]
When I run `python  cle_bc.py` and `python  qat.py` in examples/tensorflow/quantization, I get these error message. How to solve it.

`Traceback (most recent call last):
  File "cle_bc.py", line 59, in <module>
    from aimet_tensorflow import batch_norm_fold as aimet_bnf
  File "/data/aimet_tf/build/staging/universal/lib/python/aimet_tensorflow/batch_norm_fold.py", line 48, in <module>
    from aimet_tensorflow.quantsim import QuantizationSimModel
  File "/data/aimet_tf/build/staging/universal/lib/python/aimet_tensorflow/quantsim.py", line 105, in <module>
    qcops = _load_ops()
  File "/data/aimet_tf/build/staging/universal/lib/python/aimet_tensorflow/quantsim.py", line 101, in _load_ops
    return tf.load_op_library('libaimet_tf_ops.so')
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/load_library.py", line 57, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: libaimet_tf_ops.so: cannot open shared object file: No such file or directory` 

I try to copy libaimet_tf_ops.so which in build/staging/universal/lib/python/aimet_common to build/staging/universal/lib/python/aimet_tensoflow, but it cannot solve it.  

Solution: 
(1) I modify the aimet_tensorflow/quantsim.py by setting absolute path of libaimet_tf_ops.so
`return tf.load_op_library('libaimet_tf_ops.so')` => `return tf.load_op_library(''aimet/build/staging/universal/lib/python/aimet_common/libaimet_tf_ops.so')`

or
(2) set env. variable export LD_LIBRARY_PATH=$WORKSPACE/aimet/build/staging/universal/lib/python/aimet_common:$LD_LIBRARY_PATH

**Comment by Jia-HongHenryLee** [comment]
@[justacasul](https://github.com/justacasul) I solve it.
