### ISSUE TITLE
ValueError: After pruning disconnected nodes, this model is empty.

### ISSUE THREAD

**Issue by WillLiGitHub** [quic/aimet#1660]
aimet  version: 1.22.2
tensorflow-gpu:2.4.0

i want to quantize yolov3 model with aimet, then convert to dlc with snpe-tensorflow-to-dlc。
when i convert *.meta model convert to dlc, Failed.

2022-10-26 17:54:30,249 - 214 - INFO - INFO_ALL_BUILDING_NETWORK: 
    ==============================================================
    Building Network
    ==============================================================
2022-10-26 17:54:44,736 - 214 - INFO - Resolving static sub-graphs in network...
2022-10-26 17:54:49,475 - 214 - INFO - Resolving static sub-graphs in network, complete.
2022-10-26 17:54:49,496 - 219 - WARNING - WARNING_UNSUPPORTED_OPS_FOUND: Some Operations are not supported by converter. Use option --show_unconsumed_nodes to see the list of operations.
2022-10-26 17:54:49,498 - 219 - WARNING - WARNING_UNCONSUMED_LAYERS: The TF Graph has been disconnected due to some unsupported operations. Use option --show_unconsumed_nodes to see the list of disconnected layers.
2022-10-26 17:54:49,502 - 214 - INFO - Processed 15 quantization encodings
2022-10-26 17:54:49,509 - 219 - WARNING - Output node decode_0/concat_1, specified via command line, does not exist in graph.
2022-10-26 17:54:49,510 - 219 - WARNING - Output node decode_1/concat_1, specified via command line, does not exist in graph.
graph_output_nodes:  []
2022-10-26 17:54:49,510 - 209 - ERROR - Conversion FAILED!
Traceback (most recent call last):
  File "/home/pateo/work/snpe/snpe-1.61.0.3358/bin/x86_64-linux-clang/snpe-tensorflow-to-dlc", line 73, in <module>
    main()
  File "/home/pateo/work/snpe/snpe-1.61.0.3358/bin/x86_64-linux-clang/snpe-tensorflow-to-dlc", line 69, in main
    raise e
  File "/home/pateo/work/snpe/snpe-1.61.0.3358/bin/x86_64-linux-clang/snpe-tensorflow-to-dlc", line 58, in main
    optimized_graph = optimizer.optimize(ir_graph)
  File "/home/pateo/work/snpe/snpe-1.61.0.3358/lib/python/qti/aisw/converters/common/converter_ir/op_graph_optimizations.py", line 268, in optimize
    remove_disconnected_nodes(graph)
  File "/home/pateo/work/snpe/snpe-1.61.0.3358/lib/python/qti/aisw/converters/common/converter_ir/op_graph_optimizations.py", line 575, in remove_disconnected_nodes
    raise ValueError("After pruning disconnected nodes, this model is empty.")
ValueError: After pruning disconnected nodes, this model is empty.

**Comment by WillLiGitHub** [comment]
snpe version: 1.61.0.3358

**Comment by quic-akhobare** [comment]
Hi @WillLiGitHub - From the log above it appears that you are running into issues with the SNPE converter. You will need to discuss this with the SNPE team. 

I will close this ticket for now. If it turns out that this was related to a bug in AIMET, please reopen.
