### ISSUE TITLE
Getting error - OSError: image file is truncated (13 bytes not processed)

### ISSUE THREAD

**Issue by rk800506** [quic/aimet#1685]
I am trying the example notebook for quantization based on Adaround, I am not providing any input for evaluation iteration. 

**2022-11-04 17:07:24,617 - Dataloader - INFO - Dataset consists of 20121 images in 200 classes
2022-11-04 17:07:24,621 - Eval - INFO - No value of iteration is provided, running evaluation on complete dataset.
2022-11-04 17:07:24,622 - Eval - INFO - Evaluating nn.Module for 629 iterations with batch_size 32**

**The error comes at 601th iteration.**

Can someone guide on the cause of error, is it related to size of GPU memory?

`OSError: Caught OSError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/dtu-project2/aimet_testing/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/dtu-project2/aimet_testing/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/dtu-project2/aimet_testing/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/dtu-project2/aimet_testing/aimet_1_22_2/Examples/torch/utils/image_net_data_loader.py", line 155, in __getitem__
    sample = self.loader(path)
  File "/home/dtu-project2/aimet_testing/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 269, in default_loader
    return pil_loader(path)
  File "/home/dtu-project2/aimet_testing/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 251, in pil_loader
    return img.convert('RGB')
  File "/home/dtu-project2/aimet_testing/lib/python3.8/site-packages/PIL/Image.py", line 873, in convert
    self.load()
  File "/home/dtu-project2/aimet_testing/lib/python3.8/site-packages/PIL/ImageFile.py", line 245, in load
    raise OSError(
OSError: image file is truncated (13 bytes not processed)`

**Comment by rk800506** [comment]
Adding the following before evaluation solved the issue.

`from PIL import ImageFile`
`ImageFile.LOAD_TRUNCATED_IMAGES = True`

**Comment by rk800506** [comment]
Closing it.
