### ISSUE TITLE
Error when quantizing Inception_v3 PyTorch pretrained model 

### ISSUE THREAD

**Issue by zhuoran-guo** [quic/aimet#1938]
Hi, I appreciate your contribute.
I tried using quantization technique with your Aimet tool with pytorch inception_v3 pretrained model. When call function sim.compute_encodings() it throw the following error:
```
anasys@aimet-gpu-01:~/chart-ai-edge$ python3 aimet_test.py 
2023-02-22 00:22:22,917 - root - INFO - AIMET
/home/anasys/.local/lib/python3.6/site-packages/torch/fx/graph.py:606: UserWarning: Attempted to insert a call_module Node with no underlying reference in the owning GraphModule! Call GraphModule.add_submodule to add the necessary submodule
  warnings.warn("Attempted to insert a call_module Node with "
2023-02-22 00:22:27,776 - Quant - INFO - Functional         : Adding new module for node: {mul} 
2023-02-22 00:22:27,776 - Quant - INFO - Functional         : Adding new module for node: {add} 
2023-02-22 00:22:27,777 - Quant - INFO - Functional         : Adding new module for node: {mul_1} 
2023-02-22 00:22:27,777 - Quant - INFO - Functional         : Adding new module for node: {add_1} 
2023-02-22 00:22:27,777 - Quant - INFO - Functional         : Adding new module for node: {mul_2} 
2023-02-22 00:22:27,777 - Quant - INFO - Functional         : Adding new module for node: {add_2} 
2023-02-22 00:22:27,778 - Quant - INFO - Functional         : Adding new module for node: {cat} 
2023-02-22 00:22:27,778 - Quant - INFO - Functional         : Adding new module for node: {relu} 
2023-02-22 00:22:27,778 - Quant - INFO - Functional         : Adding new module for node: {relu_1} 
2023-02-22 00:22:27,778 - Quant - INFO - Functional         : Adding new module for node: {relu_2} 
2023-02-22 00:22:27,778 - Quant - INFO - Functional         : Adding new module for node: {relu_3} 
2023-02-22 00:22:27,779 - Quant - INFO - Functional         : Adding new module for node: {relu_4} 
2023-02-22 00:22:27,779 - Quant - INFO - Functional         : Adding new module for node: {relu_5} 
2023-02-22 00:22:27,779 - Quant - INFO - Functional         : Adding new module for node: {relu_6} 
.......
2023-02-22 00:22:27,799 - Quant - INFO - Functional         : Adding new module for node: {cat_11} 
2023-02-22 00:22:27,799 - Quant - INFO - Functional         : Adding new module for node: {relu_84} 
2023-02-22 00:22:27,799 - Quant - INFO - Functional         : Adding new module for node: {cat_12} 
2023-02-22 00:22:27,799 - Quant - INFO - Functional         : Adding new module for node: {relu_85} 
2023-02-22 00:22:27,800 - Quant - INFO - Functional         : Adding new module for node: {relu_86} 
2023-02-22 00:22:27,800 - Quant - INFO - Functional         : Adding new module for node: {relu_87} 
2023-02-22 00:22:27,800 - Quant - INFO - Functional         : Adding new module for node: {relu_88} 
2023-02-22 00:22:27,800 - Quant - INFO - Functional         : Adding new module for node: {cat_13} 
2023-02-22 00:22:27,801 - Quant - INFO - Functional         : Adding new module for node: {relu_89} 
2023-02-22 00:22:27,801 - Quant - INFO - Functional         : Adding new module for node: {relu_90} 
2023-02-22 00:22:27,801 - Quant - INFO - Functional         : Adding new module for node: {relu_91} 
2023-02-22 00:22:27,801 - Quant - INFO - Functional         : Adding new module for node: {relu_92} 
2023-02-22 00:22:27,801 - Quant - INFO - Functional         : Adding new module for node: {cat_14} 
2023-02-22 00:22:27,802 - Quant - INFO - Functional         : Adding new module for node: {relu_93} 
2023-02-22 00:22:27,802 - Quant - INFO - Functional         : Adding new module for node: {cat_15} 
2023-02-22 00:22:29,220 - Quant - INFO - No config file provided, defaulting to config file at /home/anasys/.local/lib/python3.6/site-packages/aimet_common/quantsim_config/default_config.json
2023-02-22 00:22:29,506 - Quant - ERROR - Expecting quantize activation input of type torch.Tensor but got <class 'float'>
Traceback (most recent call last):
  File "aimet_test.py", line 92, in <module>
    forward_pass_callback_args=use_cuda)
  File "/home/anasys/.local/lib/python3.6/site-packages/aimet_torch/quantsim.py", line 262, in compute_encodings
    _ = forward_pass_callback(self.model, forward_pass_callback_args)
  File "aimet_test.py", line 49, in pass_calibration_data
    sim_model(inputs_batch)
  File "/home/anasys/.local/lib/python3.6/site-packages/torch/fx/graph_module.py", line 513, in wrapped_call
    raise e.with_traceback(None)
AssertionError
```
My code is :
```
model = inception_v3(pretrained=True).eval()
use_cuda = False
if torch.cuda.is_available():
    use_cuda = True
    model.to(torch.device('cuda'))

# _ = fold_all_batch_norms(model, input_shapes=(1, 3, 299, 299))
prepared_model = prepare_model(model).cuda()
input_shape = (1, 3, 299, 299)
dummy_input = torch.randn(input_shape).cuda()

quant_sim = QuantizationSimModel(prepared_model, dummy_input=dummy_input,
                                 quant_scheme=QuantScheme.post_training_tf_enhanced,
                                 default_param_bw=8, default_output_bw=8)
quant_sim.compute_encodings(forward_pass_callback=pass_calibration_data,
                      forward_pass_callback_args=use_cuda)
```

```
def pass_calibration_data(sim_model, use_cuda):
    data_transform = {
        'val': transforms.Compose([
            transforms.Resize(image_size),
            transforms.CenterCrop(crop_size),
            transforms.ToTensor(),
            transforms.Normalize(mean, std)
        ])
    }
    val_dataset = torchvision.datasets.ImageFolder(root=val_image_dir, transform=data_transform['val'])
    data_loader = torch.utils.data.DataLoader(
        val_dataset, batch_size=1, shuffle=False
    )
    batch_size = data_loader.batch_size

    if use_cuda:
        device = torch.device('cuda')
    else:
        device = torch.device('cpu')

    sim_model.eval()
    samples = 1000

    batch_cntr = 0
    with torch.no_grad():
        for input_data, target_data in data_loader:

            inputs_batch = input_data.to(device)
            sim_model(inputs_batch)

            batch_cntr += 1
            if (batch_cntr * batch_size) > samples:
                break
```
And I used the model validator to check if there are some updates needed to run quantization correctly it shows the log like:
```
model = inception_v3(pretrained=True).eval()
prepared_model = prepare_model(model).cpu()
ModelValidator.validate_model(prepared_model, model_input=torch.rand(1, 3, 299, 299))
```

```
2023-02-22 03:02:30,415 - Utils - INFO - Running validator check <function validate_for_missing_modules at 0x413e166bf8>
2023-02-22 03:04:18,456 - Utils - WARNING - Ops with missing modules: ['avg_pool2d_51', 'avg_pool2d_74', 'avg_pool2d_97', 'max_pool2d_114', 'avg_pool2d_143', 'avg_pool2d_175', 'avg_pool2d_207', 'avg_pool2d_239', 'max_pool2d_262', 'avg_pool2d_290', 'avg_pool2d_321', 'flatten_328']
This can be due to several reasons:
1. There is no mapping for the op in ConnectedGraph.op_type_map. Add a mapping for ConnectedGraph to recognize and be able to map the op.
2. The op is defined as a functional in the forward function, instead of as a class module. Redefine the op as a class module if possible. Else, check 3.
3. This op is one that cannot be defined as a class module, but has not been added to ConnectedGraph.functional_ops. Add to continue.
2023-02-22 03:04:18,458 - Utils - INFO - The following validator checks failed:
2023-02-22 03:04:18,459 - Utils - INFO -        <function validate_for_missing_modules at 0x413e166bf8>
```
Do you know how to solve this problem ? 
Thank you so much

**Comment by quic-hitameht** [comment]
@zhuoran-guo Can you please confirm which AIMET version are you using? If not using the latest release, can you please use the latest AIMET 1.24.0 (https://github.com/quic/aimet/releases) and let us know if you run into the same issues.

**Comment by zhuoran-guo** [comment]
@quic-hitameht 
hello, I am using the AIMET version 1.21.0
because the 1.24.0 can not build successful:
Do you know the reason ? 
```
root@_docker:/work# python3
Python 3.8.0 (default, Dec  9 2021, 17:53:27) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()
root@_docker:/work# python3 -m pip install https://github.com/quic/aimet/releases/download/1.24.0/AimetCommon-torch_gpu_1.24.0-cp38-cp38-linux_x86_64.whl
AimetCommon-torch_gpu_1.24.0-cp38-cp38-linux_x86_64.whl is not a valid wheel filename.
```

**Comment by zhuoran-guo** [comment]
@quic-hitameht 
yes, thank you 
when I update the aimet version from 1.21.0 to 1.24.0, it works for me !
