### ISSUE TITLE
RuntimeError: Inference tensors cannot be saved for backward when doing QAT

### ISSUE THREAD

**Issue by cascosula** [quic/aimet#2026]
Hello, after installing AIMET 1.25.0 and running QAT on Python 3.8.16, I got the following error
```
Traceback (most recent call last):
  File "quantization.py", line 639, in <module>
    main()
  File "quantization.py", line 634, in main
    model.train(**args.cfg, cfg=cfg_path)  # train the model
  File "/home/gvsai/projects/ultralytics_quant/ultralytics/yolo/engine/model.py", line 319, in train
    self.trainer.train()
  File "/home/gvsai/projects/ultralytics_quant/ultralytics/yolo/engine/trainer.py", line 188, in train
    self._do_train(RANK, world_size)
  File "quantization.py", line 516, in _do_train
    super()._do_train(rank, world_size)
  File "/home/gvsai/projects/ultralytics_quant/ultralytics/yolo/engine/trainer.py", line 308, in _do_train
    preds = self.model(batch['img'])
  File "/home/gvsai/anaconda3/envs/yolov8-aimet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/gvsai/projects/ultralytics_quant/ultralytics/nn/tasks.py", line 203, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "/home/gvsai/projects/ultralytics_quant/ultralytics/nn/tasks.py", line 62, in _forward_once
    x = m(x)  # run
  File "/home/gvsai/anaconda3/envs/yolov8-aimet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/gvsai/projects/ultralytics_quant/ultralytics/nn/modules.py", line 39, in forward_fuse
    return self.act(self.conv(x))
  File "/home/gvsai/anaconda3/envs/yolov8-aimet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/gvsai/anaconda3/envs/yolov8-aimet/lib/python3.8/site-packages/aimet_torch/qc_quantize_op.py", line 825, in forward
    quantized_inputs = self._quantize_activation(torch_inputs, self.input_quantizers, 'input')
  File "/home/gvsai/anaconda3/envs/yolov8-aimet/lib/python3.8/site-packages/aimet_torch/qc_quantize_op.py", line 893, in _quantize_activation
    quantized_tensors.append(tensor_quantizers[index].quantize_dequantize(tensor_to_quantize, encoding_min,
  File "/home/gvsai/anaconda3/envs/yolov8-aimet/lib/python3.8/site-packages/aimet_torch/tensor_quantizer.py", line 744, in quantize_dequantize
    tensor = QuantizeDequantizeFunc.apply(tensor, encoding_min, encoding_max, self)
RuntimeError: Inference tensors cannot be saved for backward. To work around you can make a clone to get a normal tensor and use it in autograd.
```
I can run normal training. And I can run QAT properly in the 1.23.0 version. Is there any solution to this issue?

**Comment by quic-mangal** [comment]
@cascosula, thanks for reporting this, we will look into it and get back.

**Comment by bruce1408** [comment]
I also encountered the same problem, is there a solution now?

**Comment by quic-klhsieh** [comment]
@bruce1408 Which version of AIMET are you using? Would you be able to share a small code snippet to reproduce the issue?

**Comment by bruce1408** [comment]
> [@bruce1408](https://github.com/bruce1408) Which version of AIMET are you using? Would you be able to share a small code snippet to reproduce the issue?

The code repository I used was release-aimet-1.34 branch, and when I ran the code qat_range_learning_ddp_training_lightining.py, an error was reported, as shown below:
```
Traceback (most recent call last):
  File "/mnt/share_disk/bruce_trie/workspace/Quantizer-Tools/aimet/Examples/torch/quantization/qat_range_learning_ddp_training_lightining.py", line 281, in <module>
    main()
  File "/mnt/share_disk/bruce_trie/workspace/Quantizer-Tools/aimet/Examples/torch/quantization/qat_range_learning_ddp_training_lightining.py", line 278, in main
    trainer.fit(model)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 545, in fit
    call._call_and_handle_interrupt(
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 102, in launch
    return function(*args, **kwargs)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 581, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 990, in _run
    results = self._run_stage()
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1036, in _run_stage
    self.fit_loop.run()
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 202, in run
    self.advance()
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 359, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 136, in run
    self.advance(data_fetcher)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 240, in advance
    batch_output = self.automatic_optimization.run(trainer.optimizers[0], batch_idx, kwargs)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 187, in run
    self._optimizer_step(batch_idx, closure)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 265, in _optimizer_step
    call._call_lightning_module_hook(
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 157, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/core/module.py", line 1282, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/core/optimizer.py", line 151, in step
    step_output = self._strategy.optimizer_step(self._optimizer, closure, **kwargs)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/strategies/ddp.py", line 263, in optimizer_step
    optimizer_output = super().optimizer_step(optimizer, closure, model, **kwargs)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 230, in optimizer_step
    return self.precision_plugin.optimizer_step(optimizer, model=model, closure=closure, **kwargs)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 117, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/torch/optim/optimizer.py", line 140, in wrapper
    out = func(*args, **kwargs)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/torch/optim/optimizer.py", line 23, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/torch/optim/adam.py", line 183, in step
    loss = closure()
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 104, in _wrap_closure
    closure_result = closure()
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 140, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 126, in closure
    step_output = self._step_fn()
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 315, in _training_step
    training_step_output = call._call_strategy_hook(trainer, "training_step", *kwargs.values())
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 309, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 381, in training_step
    return self._forward_redirection(self.model, self.lightning_module, "training_step", *args, **kwargs)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 628, in __call__
    wrapper_output = wrapper_module(*args, **kwargs)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 621, in wrapped_forward
    out = method(*_args, **_kwargs)
  File "/mnt/share_disk/bruce_trie/workspace/Quantizer-Tools/aimet/Examples/torch/quantization/qat_range_learning_ddp_training_lightining.py", line 117, in training_step
    logits = self.model(images)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/torch/fx/graph_module.py", line 658, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/torch/fx/graph_module.py", line 277, in __call__
    raise e
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/torch/fx/graph_module.py", line 267, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "<eval_with_key>.1", line 5, in forward
Traceback (most recent call last):
  File "/mnt/share_disk/bruce_trie/workspace/Quantizer-Tools/aimet/Examples/torch/quantization/qat_range_learning_ddp_training_lightining.py", line 281, in <module>
    main()
  File "/mnt/share_disk/bruce_trie/workspace/Quantizer-Tools/aimet/Examples/torch/quantization/qat_range_learning_ddp_training_lightining.py", line 278, in main
    trainer.fit(model)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 545, in fit
    call._call_and_handle_interrupt(
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 102, in launch
    return function(*args, **kwargs)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 581, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 990, in _run
    results = self._run_stage()
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1036, in _run_stage
    self.fit_loop.run()
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 202, in run
    self.advance()
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 359, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 136, in run
    self.advance(data_fetcher)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 240, in advance
    batch_output = self.automatic_optimization.run(trainer.optimizers[0], batch_idx, kwargs)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 187, in run
    self._optimizer_step(batch_idx, closure)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 265, in _optimizer_step
    call._call_lightning_module_hook(
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 157, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/core/module.py", line 1282, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/core/optimizer.py", line 151, in step
    step_output = self._strategy.optimizer_step(self._optimizer, closure, **kwargs)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/strategies/ddp.py", line 263, in optimizer_step
    optimizer_output = super().optimizer_step(optimizer, closure, model, **kwargs)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 230, in optimizer_step
    return self.precision_plugin.optimizer_step(optimizer, model=model, closure=closure, **kwargs)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 117, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/torch/optim/optimizer.py", line 140, in wrapper
    out = func(*args, **kwargs)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/torch/optim/optimizer.py", line 23, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/torch/optim/adam.py", line 183, in step
    loss = closure()
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 104, in _wrap_closure
    closure_result = closure()
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 140, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 126, in closure
    step_output = self._step_fn()
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 315, in _training_step
    training_step_output = call._call_strategy_hook(trainer, "training_step", *kwargs.values())
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 309, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 381, in training_step
    return self._forward_redirection(self.model, self.lightning_module, "training_step", *args, **kwargs)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 628, in __call__
    wrapper_output = wrapper_module(*args, **kwargs)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 621, in wrapped_forward
    out = method(*_args, **_kwargs)
  File "/mnt/share_disk/bruce_trie/workspace/Quantizer-Tools/aimet/Examples/torch/quantization/qat_range_learning_ddp_training_lightining.py", line 117, in training_step
    logits = self.model(images)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/torch/fx/graph_module.py", line 658, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl

  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/torch/fx/graph_module.py", line 277, in __call__
    raise e
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/torch/fx/graph_module.py", line 267, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/aimet_torch/qc_quantize_op.py", line 1064, in forward
    return forward_call(*input, **kwargs)
  File "<eval_with_key>.1", line 5, in forward
      File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
quantized_inputs = self._quantize_activation(torch_inputs, self.input_quantizers, 'input')
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/aimet_torch/qc_quantize_op.py", line 1154, in _quantize_activation
    return forward_call(*input, **kwargs)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/aimet_torch/qc_quantize_op.py", line 1064, in forward
    quantized_tensors.append(inner_quantization(tensor_to_quantize, index))
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/aimet_torch/qc_quantize_op.py", line 1147, in inner_quantization
    quantized_inputs = self._quantize_activation(torch_inputs, self.input_quantizers, 'input')
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/aimet_torch/qc_quantize_op.py", line 1154, in _quantize_activation
    return tensor_quantizers[index].quantize_dequantize(input_tensor, encoding_min, encoding_max)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/aimet_torch/tensor_quantizer.py", line 798, in quantize_dequantize
    quantized_tensors.append(inner_quantization(tensor_to_quantize, index))
      File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/aimet_torch/qc_quantize_op.py", line 1147, in inner_quantization
tensor = QuantizeDequantizeFunc.apply(tensor, encoding_min, encoding_max, self)
RuntimeError: Inference tensors cannot be saved for backward. To work around you can make a clone to get a normal tensor and use it in autograd.
    return tensor_quantizers[index].quantize_dequantize(input_tensor, encoding_min, encoding_max)
  File "/mnt/share_disk/bruce_trie/miniforge3/envs/train_qat/lib/python3.10/site-packages/aimet_torch/tensor_quantizer.py", line 798, in quantize_dequantize
    tensor = QuantizeDequantizeFunc.apply(tensor, encoding_min, encoding_max, self)
RuntimeError: Inference tensors cannot be saved for backward. To work around you can make a clone to get a normal tensor and use it in autograd.

```

I suspect that in the inference phase, tensor is used without grade, but gradients need to be passed during training.

**Comment by quic-klhsieh** [comment]
For this specific case, the issue seems to be due to bad interaction with Pytorch Lightning's trainer class during test(), where torch.inference mode is used:

https://github.com/Lightning-AI/pytorch-lightning/issues/14497
https://github.com/Lightning-AI/pytorch-lightning/pull/15034/files

I'm able to reproduce the issue and can get past it by setting inference_mode = False when instantiating the pl.Trainer, switching it to use torch.no_grad instead of torch.inference_mode. Can you check if it works for you?

**Comment by quic-klhsieh** [comment]
Closing this issue, feel free to reopen if the issue persists.
