### ISSUE TITLE
Pytorch model with permute function  raise NotImplementedError when using channel pruning 

### ISSUE THREAD

**Issue by smallsheep666** [quic/aimet#2059]
hi,there!
I have some problem when using channel pruning when the pytorch forward function has permute op. I tried transpose op instead，but still not work.how can i fix this？
here is the forward function：
        x = self.features(x)
        x = self.classifier(x)
        batch_size = x.shape[0]
        x = torch.reshape(x,(batch_size,self.num_classes,-1))
        x = x.permute(0,2,1)
        x = torch.reshape(x,(-1,self.num_classes))
        return x
here is the traceback
Traceback (most recent call last):
  File "debug.v3.py", line 143, in <module>
    compress_model,stats = aimet_channel_pruning(model=model,evaluator = test_pipline.evaluate,data_loader = test_loader)
  File "debug.v3.py", line 53, in aimet_channel_pruning
    results = ModelCompressor.compress_model(model=model,
  File "/usr/local/lib/python3.8/dist-packages/aimet_torch/compress.py", line 113, in compress_model
    compressed_layer_db, stats = algo.compress_model(cost_metric, trainer)
  File "/usr/local/lib/python3.8/dist-packages/aimet_common/compression_algo.py", line 87, in compress_model
    layer_comp_ratio_list, stats = self._comp_ratio_select_algo.select_per_layer_comp_ratios()
  File "/usr/local/lib/python3.8/dist-packages/aimet_common/comp_ratio_select.py", line 222, in select_per_layer_comp_ratios
    eval_scores_dict = self._construct_eval_dict()
  File "/usr/local/lib/python3.8/dist-packages/aimet_common/comp_ratio_select.py", line 213, in _construct_eval_dict
    eval_scores_dict = self._compute_eval_scores_for_all_comp_ratio_candidates()
  File "/usr/local/lib/python3.8/dist-packages/aimet_common/comp_ratio_select.py", line 398, in _compute_eval_scores_for_all_comp_ratio_candidates
    layer_wise_eval_scores = self._compute_layerwise_eval_score_per_comp_ratio_candidate(data_table,
  File "/usr/local/lib/python3.8/dist-packages/aimet_common/comp_ratio_select.py", line 425, in _compute_layerwise_eval_score_per_comp_ratio_candidate
    pruned_layer_db = self._pruner.prune_model(self._layer_db,
  File "/usr/local/lib/python3.8/dist-packages/aimet_torch/channel_pruning/channel_pruner.py", line 251, in prune_model
    comp_layer_db = Pruner.prune_model(self, layer_db,
  File "/usr/local/lib/python3.8/dist-packages/aimet_common/pruner.py", line 75, in prune_model
    self._prune_layer(layer_db, comp_layer_db, layer, comp_ratio, cost_metric)
  File "/usr/local/lib/python3.8/dist-packages/aimet_torch/channel_pruning/channel_pruner.py", line 219, in _prune_layer
    self._winnow_and_reconstruct_layer(orig_layer_db, comp_layer_db, layer, comp_ratio, True)
  File "/usr/local/lib/python3.8/dist-packages/aimet_torch/channel_pruning/channel_pruner.py", line 178, in _winnow_and_reconstruct_layer
    _, module_list = winnow_model(comp_layer_db.model, self._input_shape,
  File "/usr/local/lib/python3.8/dist-packages/aimet_torch/winnow/winnow.py", line 69, in winnow_model
    mask_winnower = MaskPropagationWinnower(model, input_shape, list_of_modules_to_winnow, reshape,
  File "/usr/local/lib/python3.8/dist-packages/aimet_torch/winnow/mask_propagation_winnower.py", line 101, in __init__
    self._mask_propagator = MaskPropagator(self._graph, ModelApi.pytorch)
  File "/usr/local/lib/python3.8/dist-packages/aimet_common/winnow/mask_propagator.py", line 77, in __init__
    self._create_masks()
  File "/usr/local/lib/python3.8/dist-packages/aimet_common/winnow/mask_propagator.py", line 93, in _create_masks
    self._create_masks_for_op_and_all_ancestors(op)
  File "/usr/local/lib/python3.8/dist-packages/aimet_common/winnow/mask_propagator.py", line 118, in _create_masks_for_op_and_all_ancestors
    self._op_to_mask_dict[current_op] = Mask(current_op, self._model_api)
  File "/usr/local/lib/python3.8/dist-packages/aimet_common/winnow/mask.py", line 467, in __init__
    self._set_default_input_output_masks(self._num_in_channels, self._num_out_channels)
  File "/usr/local/lib/python3.8/dist-packages/aimet_common/winnow/mask.py", line 727, in _set_default_input_output_masks
    raise NotImplementedError(error_msg)
NotImplementedError: Unsupported op_type permute, dotted permute_81, input_ops: [reshape_76]

**Comment by quic-mangal** [comment]
@smallsheep666, thanks for reporting this. As the channel pruning code is old and has not been updated in a while, it is possible that we do not cover the scenario you have mentioned. We will look into this and try to find a solution
