### ISSUE TITLE
Aimet-tensorflow-Resnet50

### ISSUE THREAD

**Issue by keerthana-soundarrajan** [quic/aimet#2288]
Traceback (most recent call last):
  File "evaluators/resnet50_tf2_quanteval.py", line 13, in <module>
    from aimet_zoo_tensorflow.resnet50_tf2.model.model_definition import Resnet50
  File "/home/keerdhan/anaconda3/envs/ai_tf/lib/python3.8/site-packages/aimet_zoo_tensorflow/resnet50_tf2/model/model_definition.py", line 13, in <module>
    from aimet_tensorflow.keras.quantsim import QuantizationSimModel # pylint:disable = import-error
  File "/home/keerdhan/anaconda3/envs/ai_tf/lib/python3.8/site-packages/aimet_tensorflow/keras/quantsim.py", line 53, in <module>
    from aimet_tensorflow.keras.quant_sim.qc_quantize_wrapper import QcQuantizeWrapper, QuantizerSettings
  File "/home/keerdhan/anaconda3/envs/ai_tf/lib/python3.8/site-packages/aimet_tensorflow/keras/quant_sim/qc_quantize_wrapper.py", line 47, in <module>
    from aimet_tensorflow.keras.quant_sim.tensor_quantizer import ActivationTensorQuantizer, \
  File "/home/keerdhan/anaconda3/envs/ai_tf/lib/python3.8/site-packages/aimet_tensorflow/keras/quant_sim/tensor_quantizer.py", line 46, in <module>
    import aimet_common.libaimet_tf_ops as qcops
  File "/home/keerdhan/anaconda3/envs/ai_tf/lib/python3.8/site-packages/aimet_common/libaimet_tf_ops/__init__.py", line 38, in <module>
    __module = tf.load_op_library(str(pathlib.Path(__file__).parent.parent / 'libaimet_tf_ops.so'))
  File "/home/keerdhan/anaconda3/envs/ai_tf/lib/python3.8/site-packages/tensorflow/python/framework/load_library.py", line 57, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/keerdhan/anaconda3/envs/ai_tf/lib/python3.8/site-packages/aimet_common/libaimet_tf_ops.so: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringERKNS_15OpKernelContextEb

I am facing issue to execute this command, I have installed all the aimet dependencies I have the path to my dataset also but still if I try to execute the below command im getting the above error

python aimet_zoo_tensorflow/resnet50_tf2/evaluators/resnet50_tf2_quanteval.py \
    --dataset-path <path to imagenet dataset> \
    --batch-size <batch size for loading the dataset> \
    --model-config <model configuration to test>

**Comment by quic-mangal** [comment]
@quic-hanwxion, could you please take a look at this. Thanks

**Comment by quic-hanwxion** [comment]
Sure I'll take a look

**Comment by quic-hanwxion** [comment]
@keerthana-soundarrajan , it looks like your AIMET is missing some ops so it might not be built correctly. Can you share your running environment?
AIMET version:
tensorflow version:

**Comment by keerthana-soundarrajan** [comment]
Hi @quic-hanwxion I have rectified the error and its working fine. 
I had converted a model to int8 but i am facing issues in converting it to fp16 wherein I have encountered this assertion error

AssertionError                            Traceback (most recent call last)
Cell In[24], line 5
      2 from aimet_tensorflow.quantsim import QuantizationSimModel
      3 from aimet_common.defs import QuantizationDataType
----> 5 sim = QuantizationSimModel(session=BN_folded_sess_copy,
      6                            starting_op_names=starting_op_names,
      7                            output_op_names=output_op_names,
      8                            quant_scheme= QuantScheme.post_training_tf_enhanced,
      9                            default_output_bw=16,
     10                            default_param_bw=16,
     11                            use_cuda=use_cuda,
     12                            default_data_type=QuantizationDataType.float)

 

File ~/anaconda3/envs/new_env/lib/python3.8/site-packages/aimet_tensorflow/quantsim.py:194, in QuantizationSimModel.__init__(self, session, starting_op_names, output_op_names, quant_scheme, rounding_mode, default_output_bw, default_param_bw, use_cuda, config_file, default_data_type)
    191 self.quant_args = extract_global_quantizer_args(quant_scheme, self._quantsim_configurator)
    193 with self.session.graph.as_default():
--> 194     self._add_and_configure_quant_nodes(starting_op_names, output_op_names, default_param_bw, default_output_bw,
    195                                         default_data_type)
    197 self._override_quant_config_for_transformer_mask_add()

**Comment by keerthana-soundarrajan** [comment]
Hi @quic-mangal
When i exported the model using sim using aimet_tensorfow I got .meta and resnet50.data-00000-of-00001 this kind of file now how should i use the file to find fps calculation

**Comment by chengao923** [comment]
I'm having the same problem. My AIMET=1.26.1 , tensorflow-gpu=2.4.3。
$python auto_quant.py
![20240618174818](https://github.com/quic/aimet/assets/170301920/9e8d9e2d-c4df-4bac-bfbf-87d9e6ea8e75)

I see that AIMET version 1.26.1 is compatible with tensorflow 2.4, but it still reports an error when installing: aimettensorflow tf-gpu-1.26.1 requires tensorflow-gpu==2.10.1, but you have tensorflow-gpu 2.4.3 which is incompatible.

**Comment by chengao923** [comment]
I'm having the same problem. My AIMET=1.26.1 , tensorflow-gpu=2.4.3。
$python auto_quant.py
![image](https://github.com/quic/aimet/assets/170301920/7be1d03d-341e-4435-98b7-0c97fb0d877c)

I see that AIMET version 1.26.1 is compatible with tensorflow 2.4, but it still reports an error when installing: aimettensorflow tf-gpu-1.26.1 requires tensorflow-gpu==2.10.1, but you have tensorflow-gpu 2.4.3 which is incompatible.

**Comment by quic-mtuttle** [comment]
Closing this as aimet-tensorflow is deprecated. For models defined in tensorflow, we recommend exporting to onnx and using aimet-onnx to quantize the model. If you have further questions, feel free to open a new issue or join our [Slack Community](http://aihub.qualcomm.com/community/slack) (specifically the #aimet channel) to discuss easily
