### ISSUE TITLE
How to apply quant-aware-training with two inputs

### ISSUE THREAD

**Issue by iamweiweishi** [quic/aimet#2352]
I am trying to quantize one model with two input,

The model definition:

class my_model(nn.Module):
    ---init---
    def forward(input1, input2):
        ....

The dataset of dataloader definition:

class my_dataset(Dataset):
    ...
    def __getitem__(self, index):
        return input1, input2

The quantizaiton codes looks like:

```
...
apply_cross_layer_equalization(model=my_model, input_shape=[(1, 32, 64, 64), (1, 10)])
apply_bias_correction(model=my_model, data_loader=valid_data_loader_quant)
...
```

But the apply_bias_correction function might could not handle the model with two inputs:

Traceback (most recent call last):
  ...
  File "/aimet/lib/python3.8/site-packages/aimet_torch/bias_correction.py", line 263, in correct_bias
    ordered_conv_linear_nodes = get_ordered_lists_of_conv_fc(model, input_shape)
  File "/aimet/lib/python3.8/site-packages/aimet_torch/utils.py", line 622, in get_ordered_lists_of_conv_fc
    module_list = get_ordered_list_of_modules(model, dummy_input)
  File "/aimet/lib/python3.8/site-packages/aimet_torch/utils.py", line 522, in get_ordered_list_of_modules
    run_hook_for_layers_with_given_input(model, dummy_input, hook=_hook_to_collect_name_of_module)
  File "/aimet/lib/python3.8/site-packages/aimet_torch/utils.py", line 291, in run_hook_for_layers_with_given_input
    _ = model(*input_tensor)
  File "/aimet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'input2'

Is it possible to solve this issue?
Thank you.

**Comment by quic-mangal** [comment]
@iamweiweishi, Bias correction does not support multi-input models currently. However, if you would like, you can try out Adaround, which has consistently proven to be a better technique than Bias correction providing better accuracy results.

**Comment by iamweiweishi** [comment]
Great, thank you

**Comment by quic-hitameht** [comment]
Closing this as resolved. If there is another question please re-open or create a new issue.
