### ISSUE TITLE
AttributeError: 'GraphModule' object has no attribute '_current_fx_name'

### ISSUE THREAD

**Issue by zhuoran-guo** [quic/aimet#2478]
hello, I have a problem about use pytorch lighting to do QAT process
my step:

get the model use pytorch lightning Model moudle:
model = Model(config)
covert the model to quantisim use qimet api and calibration process:
prepared_model = prepare_model(model)
sim = QuantizationSimModel(
prepared_model,
dummy_input=dummy_input.cuda(),
quant_scheme=QuantScheme.training_range_learning_with_tf_init,
default_output_bw=8,
default_param_bw=8
)
finetune the quantisim use pytorch lightning api
trainer = get_trainer(config)
trainer.fit(sim.model, dataset)
but when I run the last step to finetune the model, it seems after I use QuantizationSimModel api to change the model type to 'GraphModule' and it can not use pytorch lightning api to train this model ? could you tell me how to solve the problem? 

Thank you so much 

```
Traceback (most recent call last):
  File "incam_e2e_aimet.py", line 232, in <module>
    main()
  File "incam_e2e_aimet.py", line 225, in main
    trainer.fit(sim.model, dataset)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 737, in fit
    self._call_and_handle_interrupt(
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 682, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 772, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 1120, in _run
    self._callback_connector._attach_model_callbacks()
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/connectors/callback_connector.py", line 266, in _attach_model_callbacks
    model_callbacks = self.trainer.call_hook("configure_callbacks")
  File "/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/trainer.py", line 1481, in call_hook
    prev_fx_name = pl_module._current_fx_name
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1269, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'GraphModule' object has no attribute '_current_fx_name'


```

**Comment by quic-hitameht** [comment]
Hello @zhuoran-guo `prepared_model` is of type `GraphModule` and won't have `_current_fx_name` attribute after symbolic tracing. Can you try adding that attribute and assign the value from the original_model and then perform finetuning? 

`prepared_model._current_fx_name = model._current_fx_name`
