### ISSUE TITLE
Encountered an error when attempting to convert to DLC after QAT by AIMET

### ISSUE THREAD

**Issue by xiexiaozheng** [quic/aimet#2559]
@quic-akinlawo Hi, I attempted Quantization-Aware Training (QAT) using AIMET, configured with weights set to per_channel and output set to per_tensor. Subsequently, when attempting to convert the exported encoding file and ONNX file to DLC format using snpe-onnx-to-dlc, an error occurred
config file is like this:
```
{
	"defaults": {
		"ops": {
			"is_output_quantized": "True"
		},
		"params": {
			"is_quantized": "True",
			"is_symmetric": "True"
		},
		"strict_symmetric": "False",
		"unsigned_symmetric": "False",
		"per_channel_quantization": "False"
	},
	"params": {
		"bias": {
			"is_quantized": "False"
		}
	},
	"op_type": {
		"Conv": {
			"per_channel_quantization": "True",
		}
	},
	"supergroups": [
		{
			"op_list": [
				"Conv",
				"BatchNormalization"
			]
		}
		
	],
	"model_input": {
		"is_input_quantized": "True"
	},
	"model_output": {}
}
```

```
2023-11-11 01:17:55,895 - 235 - INFO - Processing user provided quantization encodings:
2023-11-11 01:17:56,028 - 240 - WARNING - Can't simplify the model when custom ops or quantization overrides are specified, converting without simplification.
2023-11-11 01:17:56,242 - 235 - INFO - Successfully run shape inference in child process
2023-11-11 01:17:56,643 - 235 - INFO - Successfully receive the inferred model in main process
2023-11-11 01:17:56,662 - 240 - WARNING - WARNING_OPSET_VERSION: Warning multiple opset versions specified, using highest.
2023-11-11 01:17:57,500 - 235 - INFO - Processed 682 quantization encodings
2023-11-11 01:18:00,615 - 235 - INFO - INFO_INITIALIZATION_SUCCESS:
Traceback (most recent call last):
  File "./snpe-2.14.0.230828/bin/x86_64-linux-clang/snpe-onnx-to-dlc", line 65, in <module>
    backend.save(optimized_graph)
  File "/home/samsung/cc2022/zheng888.xie/model_conversion/snpe-2.14.0.230828/lib/python/qti/aisw/converters/backend/ir_to_dlc.py", line 161, in save
    ir_graph = self.get_ir_graph(graph)
  File "/home/samsung/cc2022/zheng888.xie/model_conversion/snpe-2.14.0.230828/lib/python/qti/aisw/converters/qnn_backend/qnn_backend_base.py", line 533, in get_ir_graph
    raise e
  File "/home/samsung/cc2022/zheng888.xie/model_conversion/snpe-2.14.0.230828/lib/python/qti/aisw/converters/qnn_backend/qnn_backend_base.py", line 528, in get_ir_graph
    QnnTranslations.apply_method_to_all_ops(BackendTranslationBase.ADD_OP_TO_BACKEND, graph, self)
  File "/home/samsung/cc2022/zheng888.xie/model_conversion/snpe-2.14.0.230828/lib/python/qti/aisw/converters/common/converter_ir/translation.py", line 71, in apply_method_to_all_ops
    self.apply_method_to_op(node.op.type, method_name, node, graph, *args, **kwargs)
  File "/home/samsung/cc2022/zheng888.xie/model_conversion/snpe-2.14.0.230828/lib/python/qti/aisw/converters/common/converter_ir/translation.py", line 51, in apply_method_to_op
    return translation.apply_method(method_name, *args, **kwargs)
  File "/home/samsung/cc2022/zheng888.xie/model_conversion/snpe-2.14.0.230828/lib/python/qti/aisw/converters/common/converter_ir/translation.py", line 18, in apply_method
    return self.indexed_methods[method_name](*args, **kwargs)
  File "/home/samsung/cc2022/zheng888.xie/model_conversion/snpe-2.14.0.230828/lib/python/qti/aisw/converters/qnn_backend/qnn_translations.py", line 657, in add_op_to_backend
    macs=node.op.macs)
  File "/home/samsung/cc2022/zheng888.xie/model_conversion/snpe-2.14.0.230828/lib/python/qti/aisw/converters/backend/ir_to_dlc.py", line 115, in add_node
    input_names, outputs_info):
RuntimeError: fillQuantInfo: Axis quantization is required to be symmmetric. Ensure all encodings are symmetrically quantized w/offsets of 0 or 2^bw-1
Encountered Error: fillQuantInfo: Axis quantization is required to be symmmetric. Ensure all encodings are symmetrically quantized w/offsets of 0 or 2^bw-1

```

Does per-channel quantization require that all encodings be symmetric?

**Comment by quic-akinlawo** [comment]
Hello @xiexiaozheng , if you're using per channel quantization for a given op then the quantization range needs to be symmetric i.e. offset should be zero or 2^bw - 1. From your config, it looks like you have per channel quantization turned off for all params but its set for Conv only. Can you ensure that the offset for those ops meet the above criteria?

**Comment by xiexiaozheng** [comment]
> Hello @xiexiaozheng , if you're using per channel quantization for a given op then the quantization range needs to be symmetric i.e. offset should be zero or 2^bw - 1. From your config, it looks like you have per channel quantization turned off for all params but its set for Conv only. Can you ensure that the offset for those ops meet the above criteria?

@quic-akinlawo  Hi, can I set only the weights to be per-channel while keeping activations per-tensor? And I found when I use the per-channel mode, the training process is likely put on the CPU so the process is so slow, do you know why?

**Comment by quic-akinlawo** [comment]
@xiexiaozheng Per-channel quantization is only supported for parameters so that behavior is the default.

Are you referring totraining as in QAT in AIMET? @quic-mangal can you comment on if per-channel quantization can be sped up in anyway by using the GPU?

**Comment by quic-mangal** [comment]
@xiexiaozheng, which framework are you using? We support both CPU & GPU and for TF & ONNX framework, use_cuda argument needs to be set explicitly. For PT you need to start with a model on GPU

**Comment by xiexiaozheng** [comment]
> @xiexiaozheng, which framework are you using? We support both CPU & GPU and for TF & ONNX framework, use_cuda argument needs to be set explicitly. For PT you need to start with a model on GPU

Hi, @quic-akinlawo , I use the aimet1.28 based on pytorch, when I use the mode of per-tensor, the model was on GPU, but when I enable the mode of per-channel, the training process is extremely slowly, almost a hundred times slower, and the GPU is indeed being utilized, but the usage rate is not hig., so I guess the model was put on CPU, but I'm sure the model was put on GPU (model.to('cuda'))
