### ISSUE TITLE
Interface missmatch between prepare_model & QuantizationSimModel

### ISSUE THREAD

**Issue by escorciav** [quic/aimet#2913]
why do we need to run `ConnectedGraph` if we have already `prepare_model`?
In particular, why doesn't `QuantizationSimModel` use the same interface of `prepare_model`, ie `concrete_args`?

```python
dummy_input = (input_tensor, None, None, None, False)
logging.info('Preparing model from AIMET...')
model = prepare_model(model_fp32, concrete_args=dummy_input)
model_sim = QuantizationSimModel(model=model, dummy_input=dummy_input, **quantsim_kwargs)
```

Error
```
2024-05-03 15:10:05,504 - root - INFO - Inferring quantsim config...
2024-05-03 15:10:05,504 - root - INFO - Setting up QuantizationSimModel wrapper...
/home/docker/space/voyager/venv_aimet/lib/python3.8/site-packages/aimet_torch/elementwise_ops.py:60: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  ../aten/src/ATen/native/BinaryOps.cpp:467.)
  return functional(*args, **kwargs)
Traceback (most recent call last):
  File "/home/docker/space/voyager/utils/qat_gsr.py", line 157, in <module>
    model_sim = quant_builder(
  File "/home/docker/space/voyager/utils/qat_gsr.py", line 52, in quant_builder
    model_sim = QuantizationSimModel(model=model, dummy_input=dummy_input,
  File "/home/docker/space/voyager/venv_aimet/lib/python3.8/site-packages/aimet_torch/quantsim.py", line 176, in __init__
    self.connected_graph = ConnectedGraph(self.model, dummy_input)
  File "/home/docker/space/voyager/venv_aimet/lib/python3.8/site-packages/aimet_torch/meta/connectedgraph.py", line 154, in __init__
    self._construct_graph(model, model_input)
  File "/home/docker/space/voyager/venv_aimet/lib/python3.8/site-packages/aimet_torch/meta/connectedgraph.py", line 296, in _construct_graph
    trace = torch.jit.trace(model, model_input, **jit_trace_args)
  File "/home/docker/space/voyager/venv_aimet/lib/python3.8/site-packages/torch/jit/_trace.py", line 735, in trace
    return trace_module(
  File "/home/docker/space/voyager/venv_aimet/lib/python3.8/site-packages/torch/jit/_trace.py", line 952, in trace_module
    module._c._create_method_from_trace(
RuntimeError: Type 'Tuple[Tensor, NoneType, NoneType, NoneType, bool]' cannot be traced. Only Tensors and (possibly nested) Lists, Dicts, and Tuples of Tensors can be traced
```

**Comment by escorciav** [comment]
It seems that the issue is related to `torch.jit`. A colleague recommended me to use [`torch.jit.ignore`](https://pytorch.org/docs/stable/generated/torch.jit.ignore.html)

Is there something similar for `torch.fx`?

The handy dynamic versatility of Pythonic dynamic graphs bitting my butt once more this week :angry: :snake: :peach:
If you relate with my pain, please [vote here X  :bird:  ](https://twitter.com/3scorciav/status/1786410443390546158)

**Comment by escorciav** [comment]
Fixed by using a dirty hack.

Reflection. Either I didn't understand the zen of Python (gotta level up my Pythonic knowledge), or AIMET QuantSim wrapper (& ModelPrep) are bloody confusing interfaces :laughing: 

Mate, I said to myself: _"Bro, let's abandon AIMET ship (especially the public #2642 )! Perhaps the route of `pytorch.export` + `p[ytorch.quantization` & ExecuTorch is better._
FYI There is a Qualcomm team active over there. Is it the same team?
