### ISSUE TITLE
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:

### ISSUE THREAD

**Issue by k1m0io** [quic/aimet#3255]
Hi,

I am facing the issue below when running this code.

```
    quantization_sim_model = QuantizationSimModel(
        model=model,
        quant_scheme=QuantScheme.post_training_tf_enhanced,
        dummy_input=dummy_input,
        default_output_bw=8,
        default_param_bw=8,
    )
```
So this is basically the code from the the official docs. Maybe something with the installation is wrong as I've build aimet from source?

```
Traceback (most recent call last):
  File "/workspace/main.py", line 107, in <module>
    main(config_filepath)
  File "/workspace/main.py", line 62, in main
    quantization_sim_model = QuantizationSimModel(
  File "/home/vscode/.local/lib/python3.10/site-packages/aimet_torch/quantsim.py", line 296, in __init__
    self._realize_quant_wrappers_in_model(self.model)
  File "/home/vscode/.local/lib/python3.10/site-packages/aimet_torch/quantsim.py", line 307, in _realize_quant_wrappers_in_model
    quantized_module = self._realize_quant_wrapper(module_ref)
  File "/home/vscode/.local/lib/python3.10/site-packages/aimet_torch/quantsim.py", line 315, in _realize_quant_wrapper
    return module.realize_v1_wrapper()
  File "/home/vscode/.local/lib/python3.10/site-packages/aimet_torch/quantsim_config/builder.py", line 177, in realize_v1_wrapper
    quantized_module = StaticGridQuantWrapper(self._module_to_wrap, self._weight_bw, self._activation_bw,
  File "/home/vscode/.local/lib/python3.10/site-packages/aimet_torch/qc_quantize_op.py", line 673, in __init__
    super().__init__(module_to_wrap, weight_bw, activation_bw, round_mode, quant_scheme,
  File "/home/vscode/.local/lib/python3.10/site-packages/aimet_torch/qc_quantize_op.py", line 227, in __init__
    self.output_quantizers = [tensor_quantizer_factory(activation_bw, round_mode,
  File "/home/vscode/.local/lib/python3.10/site-packages/aimet_torch/qc_quantize_op.py", line 227, in <listcomp>
    self.output_quantizers = [tensor_quantizer_factory(activation_bw, round_mode,
  File "/home/vscode/.local/lib/python3.10/site-packages/aimet_torch/qc_quantize_op.py", line 98, in tensor_quantizer_factory
    tensor_quantizer = StaticGridPerTensorQuantizer(bitwidth, round_mode, quant_scheme,
  File "/home/vscode/.local/lib/python3.10/site-packages/aimet_torch/tensor_quantizer.py", line 424, in __init__
    self._cppOp = [AimetTensorQuantizer.AimetTensorQuantizer(quant_scheme)]
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. aimet_common.AimetTensorQuantizer.AimetTensorQuantizer(arg0: DlQuantization::QuantizationMode)

Invoked with: <QuantizationMode.QUANTIZATION_TF_ENHANCED: 1>
```

Any hints?

**Comment by k1m0io** [comment]
Version: aimet 1.32.0
torch==2.2.0a0+81ea7a4

Any hints?

**Comment by quic-hitameht** [comment]
Hi @k1m0io Thanks for reporting this. AIMET has tight coupling with the torch version so you will need to use the exact same version that `AimetTensorQuantizer` is compiled against unless you are building AIMET from the source.

Feel free to reopen this if you encounter any additional issues.
