### ISSUE TITLE
channel_prunning not support SpaceToDepth, how to support?

### ISSUE THREAD

**Issue by hellolingling** [quic/aimet#356]
`2020-12-16 10:38:11,155 - Winnow - ERROR - Unsupported op_type SpaceToDepth, dotted HGNet_v6_sandwich2_300.space2depth, input_ops: [cat_25]
Traceback (most recent call last):
  File "mnist_torch.py", line 137, in <module>
    channel_pruning_auto_mode()
  File "mnist_torch.py", line 130, in channel_pruning_auto_mode
    parameters=params)
  File "/home/zhulingling/ISP/compress/build/staging/universal/lib/python/aimet_torch/compress.py", line 113, in compress_model
    compressed_layer_db, stats = algo.compress_model(cost_metric, trainer)
  File "/home/zhulingling/ISP/compress/build/staging/universal/lib/python/aimet_common/compression_algo.py", line 88, in compress_model
    layer_comp_ratio_list, stats = self._comp_ratio_select_algo.select_per_layer_comp_ratios()
  File "/home/zhulingling/ISP/compress/build/staging/universal/lib/python/aimet_common/comp_ratio_select.py", line 223, in select_per_layer_comp_ratios
    eval_scores_dict = self._construct_eval_dict()
  File "/home/zhulingling/ISP/compress/build/staging/universal/lib/python/aimet_common/comp_ratio_select.py", line 214, in _construct_eval_dict
    eval_scores_dict = self._compute_eval_scores_for_all_comp_ratio_candidates()
  File "/home/zhulingling/ISP/compress/build/staging/universal/lib/python/aimet_common/comp_ratio_select.py", line 400, in _compute_eval_scores_for_all_comp_ratio_candidates
    progress_bar, layer)
  File "/home/zhulingling/ISP/compress/build/staging/universal/lib/python/aimet_common/comp_ratio_select.py", line 429, in _compute_layerwise_eval_score_per_comp_ratio_candidate
    trainer=None)
  File "/home/zhulingling/ISP/compress/build/staging/universal/lib/python/aimet_torch/channel_pruning/channel_pruner.py", line 251, in prune_model
    layer_comp_ratio_list, cost_metric, trainer)
  File "/home/zhulingling/ISP/compress/build/staging/universal/lib/python/aimet_common/pruner.py", line 75, in prune_model
    self._prune_layer(layer_db, comp_layer_db, layer, comp_ratio, cost_metric)
  File "/home/zhulingling/ISP/compress/build/staging/universal/lib/python/aimet_torch/channel_pruning/channel_pruner.py", line 218, in _prune_layer
    self._winnow_and_reconstruct_layer(orig_layer_db, comp_layer_db, layer, comp_ratio, True)
  File "/home/zhulingling/ISP/compress/build/staging/universal/lib/python/aimet_torch/channel_pruning/channel_pruner.py", line 180, in _winnow_and_reconstruct_layer
    in_place=True)
  File "/home/zhulingling/ISP/compress/build/staging/universal/lib/python/aimet_torch/winnow/winnow.py", line 70, in winnow_model
    in_place, verbose)
  File "/home/zhulingling/ISP/compress/build/staging/universal/lib/python/aimet_torch/winnow/mask_propagation_winnower.py", line 101, in __init__
    self._mask_propagator = MaskPropagator(self._graph, ModelApi.pytorch)
  File "/home/zhulingling/ISP/compress/build/staging/universal/lib/python/aimet_common/winnow/mask_propagator.py", line 77, in __init__
    self._create_masks()
  File "/home/zhulingling/ISP/compress/build/staging/universal/lib/python/aimet_common/winnow/mask_propagator.py", line 93, in _create_masks
    self._create_masks_for_op_and_all_ancestors(op)
  File "/home/zhulingling/ISP/compress/build/staging/universal/lib/python/aimet_common/winnow/mask_propagator.py", line 118, in _create_masks_for_op_and_all_ancestors
    self._op_to_mask_dict[current_op] = Mask(current_op, self._model_api)
  File "/home/zhulingling/ISP/compress/build/staging/universal/lib/python/aimet_common/winnow/mask.py", line 467, in __init__
    self._set_default_input_output_masks(self._num_in_channels, self._num_out_channels)
  File "/home/zhulingling/ISP/compress/build/staging/universal/lib/python/aimet_common/winnow/mask.py", line 726, in _set_default_input_output_masks
    raise NotImplementedError()
NotImplementedError
`
Hi,  the error is above, how to support spacetodepth in channel prunning? 
waiting for your help

**Comment by quic-akhobare** [comment]
Hi @hellolingling 

Thanks for posting the issue and the log. Could you please paste your model definition? We are interested in how space-to-depth layer was defined.

**Comment by hellolingling** [comment]
Hi @quic-akhobare , space_to_depth layer is the same as the function in tensorflow `tf.nn.space_to_depth`.

**Comment by quic-mangal** [comment]
Closing this issue due to inactivity. Please re-open it/ create a new issue if you need further help.
