### ISSUE TITLE
The name 'fc1000/Softmax' refers to an Operation not in the graph.

### ISSUE THREAD

**Issue by JohnnMason** [quic/aimet#402]
I tried to apply cross_layer_equalization on TensorFlow using the API provided in the [document](https://quic.github.io/aimet-pages/AimetDocs/api_docs/tensorflow_cross_layer_equalization.html#tf-cle), but the error described in the title occurred.

Traceback (most recent call last):
  File "tf_equalization.py", line 143, in <module>
    cross_layer_equalization_auto()
  File "tf_equalization.py", line 69, in cross_layer_equalization_auto
    new_session = equalize_model(sess, input_op_name, output_op_name)
  File "/home/john/.local/lib/python3.6/site-packages/aimet_tensorflow/cross_layer_equalization.py", line 732, in equalize_model
    after_bn_fold_sess, folded_pairs = fold_all_batch_norms(sess, start_op_names, output_op_names)
  File "/home/john/.local/lib/python3.6/site-packages/aimet_tensorflow/batch_norm_fold.py", line 372, in fold_all_batch_norms
    bn_conv_linear_pairs = find_all_batch_norms_to_fold(sess, input_op_names, output_op_names)
  File "/home/john/.local/lib/python3.6/site-packages/aimet_tensorflow/batch_norm_fold.py", line 148, in find_all_batch_norms_to_fold
    convs_linears_bn_activation_info_dict = _find_conv_bn_pairs(sess, start_op_names, output_op_names)
  File "/home/john/.local/lib/python3.6/site-packages/aimet_tensorflow/batch_norm_fold.py", line 119, in _find_conv_bn_pairs
    conn_graph = ConnectedGraph(model.graph, start_op_names, output_op_names)
  File "/home/john/.local/lib/python3.6/site-packages/aimet_tensorflow/common/connectedgraph.py", line 73, in __init__
    self._valid_ops = get_valid_ops(self._graph, self._starting_op_names, output_op_names)
  File "/home/john/.local/lib/python3.6/site-packages/aimet_tensorflow/utils/common.py", line 329, in get_valid_ops
    op = graph.get_operation_by_name(name)
  File "/home/john/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3735, in get_operation_by_name
    return self.as_graph_element(name, allow_tensor=False, allow_operation=True)
  File "/home/john/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3607, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/home/john/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3667, in _as_graph_element_locked
    "graph." % repr(name))
KeyError: "The name 'fc1000/Softmax' refers to an Operation not in the graph."

**Comment by quic-ssiddego** [comment]
Hi @JohnnMason Thank you for your query. There seems to be an issue finding the op corresponding to the output_op_name passed to the api, for your model. output_op_name passed to the CLE api should be the name of the output operation of your model. One quick check you could try is to use : **op = graph.get_operation_by_name(output_op_name)** and see that op indeed exists in your model graph.  Pass this as the input to CLE api. Please let us know if you have further questions.

**Comment by JohnnMason** [comment]
Thanks for your feedback. I used sess.graph.get_operations()  to find all ops, and it shows that output_op_name is "probs/Softmax", but which is named fc1000/Softmax in [doc](https://quic.github.io/aimet-pages/AimetDocs/api_docs/tensorflow_cross_layer_equalization.html#tf-cle). Maybe it has been changed by keras or for other reasons.
After the verification of the example, I tried to import the local model for optimization, but the problem is shown below:
```
Traceback (most recent call last):
  File "tf_equalization.py", line 207, in <module>
    cross_layer_equalization_load()
  File "tf_equalization.py", line 124, in cross_layer_equalization_load
    new_session = equalize_model(sess, input_op_name, output_op_name)
  File "/home/john/.local/lib/python3.6/site-packages/aimet_tensorflow/cross_layer_equalization.py", line 732, in equalize_model
    after_bn_fold_sess, folded_pairs = fold_all_batch_norms(sess, start_op_names, output_op_names)
  File "/home/john/.local/lib/python3.6/site-packages/aimet_tensorflow/batch_norm_fold.py", line 374, in fold_all_batch_norms
    after_fold_sess = _fold_given_auto_selected_batch_norms(sess, bn_conv_linear_pairs)
  File "/home/john/.local/lib/python3.6/site-packages/aimet_tensorflow/batch_norm_fold.py", line 295, in _fold_given_auto_selected_batch_norms
    after_bn_fold_sess = save_and_load_graph('./temp_bn_fold', sess)
  File "/home/john/.local/lib/python3.6/site-packages/aimet_tensorflow/utils/graph_saver.py", line 103, in save_and_load_graph
    save_model_to_meta(model=sess, meta_path=str(meta_path + '/temp'))
  File "/home/john/.local/lib/python3.6/site-packages/aimet_tensorflow/utils/graph_saver.py", line 58, in save_model_to_meta
    saver = tf.compat.v1.train.Saver()
  File "/home/john/.local/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 828, in __init__
    self.build()
  File "/home/john/.local/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/john/.local/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 865, in _build
    raise ValueError("No variables to save")
ValueError: No variables to save
```
And my test code is as follows:
```
def cross_layer_equalization_load():
    tf_graph_def = tf.GraphDef()
    with tf.gfile.Open("mobilenet_v1_1.0_224_frozen.pb", 'rb') as fd:
        tf_graph_def.ParseFromString(fd.read())
        with tf.Session() as sess:
            tf.import_graph_def(tf_graph_def, name='')

            input_op_name = 'MobilenetV1/MobilenetV1/Conv2d_0/Conv2D'
            output_op_name = 'MobilenetV1/Predictions/Reshape_1'

            with sess.as_default():
                new_session = equalize_model(sess, input_op_name, output_op_name)
            sess.close()
```
Is that because of that the API does not support the PB model? 
Looking forward to your reply, thanks.

**Comment by quic-ssiddego** [comment]
@JohnnMason  That's right, we do not support model in .pb format. We need to make edits to the model in the backend and would need the model passed-in as a checkpoint/meta format. Could you please try with a checkpoint/meta format and let us know.

**Comment by JohnnMason** [comment]
I have tried to use checkpoint/meta format, but new problems have arisen that lead to failure. Moreover, we really hope to use PB format directly and have communicated with you through official channels, and I will close this issue, thanks.
