### ISSUE TITLE
An assertion error in fusedbatchnorm.py

### ISSUE THREAD

**Issue by suakim** [quic/aimet#463]
Hello, I tried equalize_model function from aimet_tensorflow.cross_layer_equalization, but this occured an error in batch normalization. I tried a sample code with my model (keras) as below. And I have no idea what is wrong in the code. Could you please guide me what the problem is? Thank you in advance.

**code:** 

```
from aimet_tensorflow.cross_layer_equalization import equalize_model
from aimet_tensorflow.cross_layer_equalization import GraphSearchUtils, CrossLayerScaling, HighBiasFold
from aimet_tensorflow.batch_norm_fold import fold_all_batch_norms

sess = tf.compat.v1.keras.backend.get_session()
input_op_name = ['input_0', 'input_1', 'input_2', 'input_3']
output_op_name = 'multiply/mul'

with sess.as_default():
    new_session = equalize_model(sess, input_op_name, output_op_name)
    
sess.close()

```
**The log including the error is as below:**

```
2021-02-18 17:15:19,384 - tensorflow - WARNING - From /usr/local/lib/python3.6/dist-packages/tensorflow_core/contrib/layers/python/layers/layers.py:650: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
2021-02-18 17:15:22,528 - Utils - INFO - ...... subset to store [conv2d_2/Conv2D, batch_normalization_2]
2021-02-18 17:15:22,529 - Utils - INFO - ...... subset to store [conv2d_2/Conv2D, batch_normalization_2]
2021-02-18 17:15:22,530 - Utils - INFO - ...... subset to store [conv2d_3/Conv2D, batch_normalization_3]
2021-02-18 17:15:22,531 - Utils - INFO - ...... subset to store [conv2d_3/Conv2D, batch_normalization_3]
2021-02-18 17:15:22,532 - Utils - INFO - ...... subset to store [conv2d_4/Conv2D, batch_normalization_4]
2021-02-18 17:15:22,534 - Utils - INFO - ...... subset to store [conv2d_4/Conv2D, batch_normalization_4]
2021-02-18 17:15:22,534 - Utils - INFO - ...... subset to store [conv2d_5/Conv2D, batch_normalization_5]
2021-02-18 17:15:22,535 - Utils - INFO - ...... subset to store [conv2d_5/Conv2D, batch_normalization_5]
2021-02-18 17:15:22,536 - Utils - INFO - ...... subset to store [conv2d_16/Conv2D, batch_normalization_16]
2021-02-18 17:15:22,537 - Utils - INFO - ...... subset to store [conv2d_16/Conv2D, batch_normalization_16]
2021-02-18 17:15:22,540 - Utils - INFO - ...... subset to store [conv2d_6/Conv2D, batch_normalization_6]
2021-02-18 17:15:22,540 - Utils - INFO - ...... subset to store [conv2d_6/Conv2D, batch_normalization_6]
2021-02-18 17:15:22,542 - Utils - INFO - ...... subset to store [conv2d_7/Conv2D, batch_normalization_7]
2021-02-18 17:15:22,543 - Utils - INFO - ...... subset to store [conv2d_7/Conv2D, batch_normalization_7]
2021-02-18 17:15:22,544 - Utils - INFO - ...... subset to store [conv2d_14/Conv2D, batch_normalization_14]
2021-02-18 17:15:22,546 - Utils - INFO - ...... subset to store [conv2d_14/Conv2D, batch_normalization_14]
2021-02-18 17:15:22,547 - Utils - INFO - ...... subset to store [conv2d_15/Conv2D, batch_normalization_15]
2021-02-18 17:15:22,548 - Utils - INFO - ...... subset to store [conv2d_15/Conv2D, batch_normalization_15]
2021-02-18 17:15:22,550 - Utils - INFO - ...... subset to store [conv2d_8/Conv2D, batch_normalization_8]
2021-02-18 17:15:22,550 - Utils - INFO - ...... subset to store [conv2d_8/Conv2D, batch_normalization_8]
2021-02-18 17:15:22,552 - Utils - INFO - ...... subset to store [conv2d_9/Conv2D, batch_normalization_9]
2021-02-18 17:15:22,553 - Utils - INFO - ...... subset to store [conv2d_9/Conv2D, batch_normalization_9]
2021-02-18 17:15:22,553 - Utils - INFO - ...... subset to store [conv2d_10/Conv2D, batch_normalization_10]
2021-02-18 17:15:22,554 - Utils - INFO - ...... subset to store [conv2d_10/Conv2D, batch_normalization_10]
2021-02-18 17:15:22,556 - Utils - INFO - ...... subset to store [conv2d_11/Conv2D, batch_normalization_11]
2021-02-18 17:15:22,556 - Utils - INFO - ...... subset to store [conv2d_11/Conv2D, batch_normalization_11]
2021-02-18 17:15:22,558 - Utils - INFO - ...... subset to store [conv2d_12/Conv2D, batch_normalization_12]
2021-02-18 17:15:22,559 - Utils - INFO - ...... subset to store [conv2d_12/Conv2D, batch_normalization_12]
2021-02-18 17:15:22,559 - Utils - INFO - ...... subset to store [conv2d_13/Conv2D, batch_normalization_13]
2021-02-18 17:15:22,561 - Utils - INFO - ...... subset to store [conv2d_13/Conv2D, batch_normalization_13]
2021-02-18 17:15:22,562 - Utils - INFO - ...... subset to store [conv2d_1/Conv2D, batch_normalization_1]
2021-02-18 17:15:22,562 - Utils - INFO - ...... subset to store [conv2d_1/Conv2D, batch_normalization_1]
2021-02-18 17:15:22,564 - Utils - INFO - ...... subset to store [conv2d/Conv2D, batch_normalization]
2021-02-18 17:15:22,565 - Utils - INFO - ...... subset to store [conv2d/Conv2D, batch_normalization]
2021-02-18 17:15:22,873 - tensorflow - WARNING - From /usr/local/lib/python3.6/dist-packages/aimet_tensorflow/utils/op/conv.py:153: Variable.load (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Prefer Variable.assign which has equivalent behavior in 2.X.
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-28-ce45da7b18de> in <module>()
     15 with sess.as_default():
---> 16     new_session = equalize_model(sess, input_op_name, output_op_name)
     17 
     18 sess.close()

5 frames
/usr/local/lib/python3.6/dist-packages/aimet_tensorflow/utils/op/fusedbatchnorm.py in get_assign_moving_avg_op(bn_op)
    621             else:
    622                 sub_op = child_op
--> 623             assert sub_op.type == 'Sub'
    624             mul_op = sub_op.outputs[0].consumers()[0]
    625             assert mul_op.type == 'Mul'

AssertionError: 
```

**Comment by quic-ssiddego** [comment]
Hi @suakim Thank you for your query. AIMET currently supports https://www.tensorflow.org/api_docs/python/tf/keras/layers/BatchNormalization in fused and non-fused forms.  Could you please replace the BNs in your model to adhere to these types and give this a try? Please let us know if you have further questions.

**Comment by suakim** [comment]
Hello @quic-ssiddego, unfortunately, I got the same error when I replaced them to fused forms by using 'fused=True'. Otherwise, I should replace them with non-fused forms to skip the bias fold.

**Comment by quic-ssiddego** [comment]
Hi @suakim - is the BN layer you are using a keras type?Also, there is a new fix coming up that could potentially help with this. https://github.com/quic/aimet/pull/486. Could you please use this update once  merged and let us know if you still have issues. Thank you.

**Comment by suakim** [comment]
@quic-ssiddego yes, I am using tensorflow.keras.layers.BatchNormalization. Thank you for the reply. I will try it again once it is updated.

**Comment by xing-shuai** [comment]
@suakim I have the same issue, probably you defined optimizer(like ADAM) part in the session before equalize_model function, tring to remove the code of optimizer part. assert sub_op.type == 'Sub':  sub_op is something related to ADAM in my situation

**Comment by sunzhe09** [comment]
I met the same problem,and I use tf_slim build my backbone model，and my aimet version is 1.19.1pro，here is my error log：
2022-03-11 06:53:18,385 - Utils - INFO - ...... subset to store [MobilenetV2/expanded_conv_2/project/Conv2D, MobilenetV2/expanded_conv_2/project/BatchNorm]
Traceback (most recent call last):
File "CenterNetKerasAimet.py", line 336, in <module>
perform_qat(_config)
File "CenterNetKerasAimet.py", line 243, in perform_qat
BN_folded_sess, _ = aimet_bnf.fold_all_batch_norms(sess, input_op_names=['MobilenetV2/input'], output_op_names=outnames)
File "/opt/conda/lib/python3.6/site-packages/aimet_tensorflow/batch_norm_fold.py", line 383, in fold_all_batch_norms
after_fold_sess = _fold_given_auto_selected_batch_norms(sess, bn_conv_linear_pairs)
File "/opt/conda/lib/python3.6/site-packages/aimet_tensorflow/batch_norm_fold.py", line 296, in _fold_given_auto_selected_batch_norms
BNUtils.skip_bn_op(sess, batchnorm.op, batchnorm.in_tensor, batchnorm.out_tensor)
File "/opt/conda/lib/python3.6/site-packages/aimet_tensorflow/utils/op/fusedbatchnorm.py", line 75, in skip_bn_op
BNUtils.remove_bn_op_from_update_ops(sess, bn_op)
File "/opt/conda/lib/python3.6/site-packages/aimet_tensorflow/utils/op/fusedbatchnorm.py", line 719, in remove_bn_op_from_update_ops
assign_moving_avg_op = BNUtils.get_assign_moving_avg_op(bn_op)
File "/opt/conda/lib/python3.6/site-packages/aimet_tensorflow/utils/op/fusedbatchnorm.py", line 677, in get_assign_moving_avg_op
assert sub_op.type == 'Sub'
AssertionErro

**Comment by quic-mangal** [comment]
Closing this issue due to inactivity. Please re-open it/ create a new issue if you need further help.
