### ISSUE TITLE
fold batch norms error

### ISSUE THREAD

**Issue by tsujie** [quic/aimet#500]
Hi there, 
I try to run tensorflow equalize_model API on my model. Unfortunately, I get this error when folding batch norms
`Traceback (most recent call last):
  File "test.py", line 216, in <module>
    QuantizeModel(model, None, './image-00001.jpg', 192, 'CPM_stages/CPM_s4/CPM_s4_hm_up/CPM_s4_hm_up/Identity')
  File "test.py", line 86, in QuantizeModel
    new_session = equalize_model(sess, ['image'], ['CPM_stages/CPM_s4/CPM_s4_hm_up/CPM_s4_hm_up/Identity'])
  File "/usr/local/lib/python3.6/dist-packages/aimet_tensorflow/cross_layer_equalization.py", line 732, in equalize_model
    after_bn_fold_sess, folded_pairs = fold_all_batch_norms(sess, start_op_names, output_op_names)
  File "/usr/local/lib/python3.6/dist-packages/aimet_tensorflow/batch_norm_fold.py", line 385, in fold_all_batch_norms
    after_fold_sess = _fold_given_auto_selected_batch_norms(sess, bn_conv_linear_pairs)
  File "/usr/local/lib/python3.6/dist-packages/aimet_tensorflow/batch_norm_fold.py", line 293, in _fold_given_auto_selected_batch_norms
    numpy_weight_reshaped = np.reshape(weight_tensor.data, weight_tensor.shape).transpose((2, 3, 1, 0))
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 292, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 66, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 46, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
`
I check my model the shape should be (1,1,512,21) but AIMET gets (1,1,512,13). 
![Screen Shot 2021-03-12 at 5 35 41 PM](https://user-images.githubusercontent.com/3577980/111014628-7d277d00-8359-11eb-9147-6bf3f1bf38e9.png)

Any idea about how to fix it?
Thanks!

**Comment by tsujie** [comment]
NVM, it is my model issue.
