### ISSUE TITLE
Fatal Python error: initsite: Failed to import the site module

### ISSUE THREAD

**Issue by htpauleta** [quic/aimet#731]
Python 3.7.11 (default, Jul 27 2021, 14:32:16) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from aimet_torch.quantsim import QuantizationSimModel
2021-09-03 11:42:31,873 - root - INFO - AIMET
>>> 

显示 from aimet_torch.quantsim import QuantizationSimModel 成功

然后运行 python test.py
就报告如下错误：
Fatal Python error: initsite: Failed to import the site module
Traceback (most recent call last):
  File "/home/jiwen/anaconda3/envs/aimet/lib/python3.7/site-packages/aimet_common/x86_64-linux-gnu/site.py", line 73, in <module>
    __boot()
  File "/home/jiwen/anaconda3/envs/aimet/lib/python3.7/site-packages/aimet_common/x86_64-linux-gnu/site.py", line 47, in __boot
    addsitedir(item)
  File "/home/jiwen/anaconda3/envs/aimet/lib/python3.7/site.py", line 207, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/home/jiwen/anaconda3/envs/aimet/lib/python3.7/site.py", line 163, in addpackage
    for n, line in enumerate(f):
  File "/home/jiwen/anaconda3/envs/aimet/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte

请问有人碰到这个问题麽，谢谢

**Comment by quic-ssiddego** [comment]
@quic-bharathr  could you please take a look at this issue?

**Comment by Nachmath** [comment]
@htpauleta 这个问题你有没有解决？

**Comment by Nachmath** [comment]
> 

原因找到了，python的所有包路径，应保持英文字符，不能使用中文等

**Comment by quic-mangal** [comment]
Closing this issue due to inactivity. Please re-open it/ create a new issue if you need further help.
